### ISSUE TITLE
Make Reader page breaks in Firefox consistent with Chrome and Safari

### ISSUE THREAD

**Issue by msimmer** [triplecanopy/b-ber#311]
## Expected Behavior

Page breaks should function on all current browsers

## Actual Behavior

- Firefox doesn't respect CSS rules `column-break: before` or `column-break: after`
- Firefox does respect `break-inside: avoid` which is the equivalent of `column-break: before`
- For Firefox, in order for `break-inside: avoid` to be respected, the combined height of the content with `break-inside: avoid` applied, and the preceding content must exceed the height CSS column.

Here is a [fiddle](https://jsfiddle.net/cammer/nrqbod0p/90/) demonstrating this behavior.

## Suggested Fix(es)

Add two additions to the [current](https://github.com/triplecanopy/b-ber/blob/45027d8c31eeb56c749f351cc7944b9abf2b89af/packages/b-ber-themes/b-ber-theme-serif/layout/_layout.scss#L16) `.break-after` class for FF browsers ` @-moz-document url-prefix()`:
1. Add `margin-bottom:100vh` directly to the `.break-after` class
2. Target elements directly following `.break-after` (could be targeted by `.subchapter` or another new class specifier), and apply `break-inside: avoid`.

```scss
.break-after {
    page-break-after: always !important; // sass-lint:disable-line no-important	    
    @if $build == 'reader' {
        @include break('desktop') {
            // Reader: Chrome & Safari
            break-after: column; // not respected by FF
             // FireFox
            @-moz-document url-prefix() {
                margin-bottom: 100vh;
                + .subchapter {
                    break-inside: avoid: // respected by FF as column-break: before under special conditions
                }
            }
        }
    } @else {
        // Epub, Mobi, PDF ...
        page-break-after: always;
    }
  }	
}
```

Testing would need to be done to ensure that the inclusion of a `margin-bottom` wouldn't be broken by #270 

## Project Repository

This affects all projects

## Steps to Reproduce the Problem

1. Create project
2. Add the `break-after` class to an element
3. View the reader in Firefox

## Environment

-   Node version: v10.15.3
-   npm version: 6.10.2
-   b-ber version: >=0.1.8
-   Project config: N/A
