### ISSUE TITLE
Refine config.yml website URLS

### ISSUE THREAD

**Issue by camilamercado** [triplecanopy/b-ber#319]
`config.yml` website URLs are too repetitive.

@msimmer– pulled / edited from our discussion:

> I think we just need:
> 
> - remote_url (the base url for the project in the bucket)
> - base_path (for the reader, this is written using to the user's url bar and doesn't necessarily have to do with the project paths)
> - project_slug (this would just be the name of the project as a url)

```yml
remote_url: http://b-ber-projects-staging.s3-website-us-east-1.amazonaws.com/
base_path: /contents/
project_slug: project-name
```
`<remote url><project slug><build type>` 
Build type should be handled by deployment tasks ex: `project-reader`, `project-web`

Example output:
`http://b-ber-projects-staging.s3-website-us-east-1.amazonaws.com/all-directives-final/project-reader`
